#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : woff2
Version  : 1.0.2
Release  : 4
URL      : https://github.com/google/woff2/archive/v1.0.2.tar.gz
Source0  : https://github.com/google/woff2/archive/v1.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: woff2-lib = %{version}-%{release}
Requires: woff2-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkg-config
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)

%description
compression related modules in this repository.
brotli/ contains reference code for the Brotli byte-level compression
algorithm. Note that it is licensed under the MIT license.

%package dev
Summary: dev components for the woff2 package.
Group: Development
Requires: woff2-lib = %{version}-%{release}
Provides: woff2-devel = %{version}-%{release}
Requires: woff2 = %{version}-%{release}

%description dev
dev components for the woff2 package.


%package lib
Summary: lib components for the woff2 package.
Group: Libraries
Requires: woff2-license = %{version}-%{release}

%description lib
lib components for the woff2 package.


%package license
Summary: license components for the woff2 package.
Group: Default

%description license
license components for the woff2 package.


%prep
%setup -q -n woff2-1.0.2
cd %{_builddir}/woff2-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604356467
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1604356467
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/woff2
cp %{_builddir}/woff2-1.0.2/LICENSE %{buildroot}/usr/share/package-licenses/woff2/0abd7c6131fb3c79cc0bf5917fde1f86e1f76c2e
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/woff2/decode.h
/usr/include/woff2/encode.h
/usr/include/woff2/output.h
/usr/lib64/libwoff2common.so
/usr/lib64/libwoff2dec.so
/usr/lib64/libwoff2enc.so
/usr/lib64/pkgconfig/libwoff2common.pc
/usr/lib64/pkgconfig/libwoff2dec.pc
/usr/lib64/pkgconfig/libwoff2enc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libwoff2common.so.1.0.2
/usr/lib64/libwoff2dec.so.1.0.2
/usr/lib64/libwoff2enc.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/woff2/0abd7c6131fb3c79cc0bf5917fde1f86e1f76c2e
